#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Auth:Gryph0n
from pymouse import PyMouse
from win32api import GetSystemMetrics
import random
import time

m = PyMouse()
m.position()

width = GetSystemMetrics(0)
heigth = GetSystemMetrics(1)

m.move(100, 100)
while True:
    x = random.randint(0, width)
    y = random.randint(0, heigth)
    m.move(x, y)
    time.sleep(random.randint(3, 5))
